// Auto-generated border data from Natural Earth
// Generated from: borders_from_countries.json
// Total borders: 490

use std::collections::HashMap;

/// Load pre-computed nation adjacency data
pub fn get_nation_borders() -> Vec<(&'static str, &'static str)> {
    vec![
        ("Fiji", "Peru"),
        ("Brazil", "Fiji"),
        ("Fiji", "Vanuatu"),
        ("Fiji", "Namibia"),
        ("Australia", "Fiji"),
        ("Fiji", "Zimbabwe"),
        ("Fiji", "Madagascar"),
        ("Fiji", "Mozambique"),
        ("Fiji", "Malawi"),
        ("Botswana", "Fiji"),
        ("Angola", "Fiji"),
        ("Bolivia", "Fiji"),
        ("Chile", "Fiji"),
        ("Fiji", "Zambia"),
        ("Chile", "Peru"),
        ("Brazil", "Chile"),
        ("Argentina", "Chile"),
        ("Bolivia", "Chile"),
        ("Brazil", "Peru"),
        ("Brazil", "Suriname"),
        ("Brazil", "Colombia"),
        ("Brazil", "Venezuela"),
        ("Argentina", "Brazil"),
        ("Brazil", "Guyana"),
        ("Brazil", "Paraguay"),
        ("Bolivia", "Brazil"),
        ("Brazil", "Uruguay"),
        ("Brazil", "France"),
        ("Bolivia", "Peru"),
        ("Argentina", "Bolivia"),
        ("Bolivia", "Paraguay"),
        ("Ecuador", "Peru"),
        ("Colombia", "Peru"),
        ("Mozambique", "Zimbabwe"),
        ("Malawi", "Zimbabwe"),
        ("Botswana", "Zimbabwe"),
        ("Zambia", "Zimbabwe"),
        ("South Africa", "Zimbabwe"),
        ("Botswana", "Namibia"),
        ("Angola", "Botswana"),
        ("Botswana", "Zambia"),
        ("Botswana", "South Africa"),
        ("Angola", "Namibia"),
        ("Namibia", "Zambia"),
        ("Namibia", "South Africa"),
        ("Tanzania", "Zambia"),
        ("Mozambique", "Zambia"),
        ("Malawi", "Zambia"),
        ("Dem. Rep. Congo", "Zambia"),
        ("Angola", "Zambia"),
        ("Malawi", "Tanzania"),
        ("Malawi", "Mozambique"),
        ("Mozambique", "Tanzania"),
        ("Mozambique", "eSwatini"),
        ("Dem. Rep. Congo", "Mozambique"),
        ("Mozambique", "South Africa"),
        ("Angola", "Dem. Rep. Congo"),
        ("Angola", "Congo"),
        ("Kenya", "Tanzania"),
        ("Rwanda", "Tanzania"),
        ("Burundi", "Tanzania"),
        ("Dem. Rep. Congo", "Tanzania"),
        ("Tanzania", "Uganda"),
        ("Dem. Rep. Congo", "Nigeria"),
        ("Dem. Rep. Congo", "Gabon"),
        ("Dem. Rep. Congo", "Rwanda"),
        ("Central African Rep.", "Dem. Rep. Congo"),
        ("Cameroon", "Dem. Rep. Congo"),
        ("Burundi", "Dem. Rep. Congo"),
        ("Dem. Rep. Congo", "S. Sudan"),
        ("Congo", "Dem. Rep. Congo"),
        ("Dem. Rep. Congo", "Uganda"),
        ("Ethiopia", "Kenya"),
        ("Kenya", "S. Sudan"),
        ("Kenya", "Somalia"),
        ("Kenya", "Uganda"),
        ("Burundi", "Rwanda"),
        ("Ethiopia", "Uganda"),
        ("Rwanda", "Uganda"),
        ("S. Sudan", "Uganda"),
        ("Mauritania", "W. Sahara"),
        ("Mali", "W. Sahara"),
        ("Morocco", "W. Sahara"),
        ("France", "W. Sahara"),
        ("Algeria", "W. Sahara"),
        ("Austria", "France"),
        ("France", "Suriname"),
        ("France", "Senegal"),
        ("France", "Ghana"),
        ("France", "Germany"),
        ("Benin", "France"),
        ("Eq. Guinea", "France"),
        ("France", "United Kingdom"),
        ("France", "Liberia"),
        ("Belgium", "France"),
        ("France", "Netherlands"),
        ("France", "Libya"),
        ("France", "Sierra Leone"),
        ("France", "Gambia"),
        ("France", "Luxembourg"),
        ("France", "Portugal"),
        ("France", "Niger"),
        ("France", "Mali"),
        ("Burkina Faso", "France"),
        ("France", "Tunisia"),
        ("Canada", "France"),
        ("Côte d'Ivoire", "France"),
        ("France", "Nigeria"),
        ("France", "Mauritania"),
        ("France", "Russia"),
        ("Cameroon", "France"),
        ("France", "Guinea"),
        ("France", "Togo"),
        ("France", "Spain"),
        ("Algeria", "France"),
        ("France", "Gabon"),
        ("France", "Guinea-Bissau"),
        ("France", "Italy"),
        ("France", "Morocco"),
        ("France", "Switzerland"),
        ("Mali", "Morocco"),
        ("Mali", "Senegal"),
        ("Mali", "Nigeria"),
        ("Ghana", "Mali"),
        ("Mali", "Mauritania"),
        ("Mali", "Niger"),
        ("Benin", "Mali"),
        ("Burkina Faso", "Mali"),
        ("Guinea", "Mali"),
        ("Mali", "Togo"),
        ("Côte d'Ivoire", "Mali"),
        ("Algeria", "Mali"),
        ("Mauritania", "Senegal"),
        ("Burkina Faso", "Mauritania"),
        ("Mauritania", "Morocco"),
        ("Algeria", "Mauritania"),
        ("Algeria", "Niger"),
        ("Algeria", "Portugal"),
        ("Algeria", "Tunisia"),
        ("Algeria", "Libya"),
        ("Algeria", "Italy"),
        ("Algeria", "Morocco"),
        ("Algeria", "Spain"),
        ("Canada", "Russia"),
        ("Canada", "United States of America"),
        ("Canada", "Greenland"),
        ("Dominican Rep.", "United States of America"),
        ("Mexico", "United States of America"),
        ("Russia", "United States of America"),
        ("Haiti", "United States of America"),
        ("Bahamas", "United States of America"),
        ("Greenland", "United States of America"),
        ("Cuba", "United States of America"),
        ("Austria", "Russia"),
        ("North Macedonia", "Russia"),
        ("Germany", "Russia"),
        ("Estonia", "Russia"),
        ("China", "Russia"),
        ("Japan", "Russia"),
        ("Armenia", "Russia"),
        ("Russia", "Turkey"),
        ("Russia", "United Kingdom"),
        ("Belgium", "Russia"),
        ("Netherlands", "Russia"),
        ("Greenland", "Russia"),
        ("Montenegro", "Russia"),
        ("Hungary", "Russia"),
        ("Greece", "Russia"),
        ("Albania", "Russia"),
        ("Luxembourg", "Russia"),
        ("Bosnia and Herz.", "Russia"),
        ("Kosovo", "Russia"),
        ("Portugal", "Russia"),
        ("Russia", "Slovakia"),
        ("North Korea", "Russia"),
        ("Croatia", "Russia"),
        ("Russia", "Sweden"),
        ("Russia", "Uzbekistan"),
        ("Russia", "Serbia"),
        ("Ireland", "Russia"),
        ("Russia", "Ukraine"),
        ("Georgia", "Russia"),
        ("Russia", "Turkmenistan"),
        ("Poland", "Russia"),
        ("Russia", "Switzerland"),
        ("Kyrgyzstan", "Russia"),
        ("Czechia", "Russia"),
        ("Mongolia", "Russia"),
        ("Iceland", "Russia"),
        ("Russia", "Spain"),
        ("Norway", "Russia"),
        ("Lithuania", "Russia"),
        ("Russia", "Slovenia"),
        ("Denmark", "Russia"),
        ("Kazakhstan", "Russia"),
        ("Romania", "Russia"),
        ("Azerbaijan", "Russia"),
        ("Finland", "Russia"),
        ("Belarus", "Russia"),
        ("Italy", "Russia"),
        ("Latvia", "Russia"),
        ("Bulgaria", "Russia"),
        ("Moldova", "Russia"),
        ("Greenland", "Iceland"),
        ("Dominican Rep.", "Haiti"),
        ("Cuba", "Haiti"),
        ("Belize", "Mexico"),
        ("Mexico", "Nicaragua"),
        ("Guatemala", "Mexico"),
        ("Honduras", "Mexico"),
        ("China", "Kazakhstan"),
        ("Georgia", "Kazakhstan"),
        ("Armenia", "Kazakhstan"),
        ("Kazakhstan", "Turkmenistan"),
        ("Azerbaijan", "Kazakhstan"),
        ("Kazakhstan", "Kyrgyzstan"),
        ("Kazakhstan", "Uzbekistan"),
        ("Kazakhstan", "Tajikistan"),
        ("Iran", "Uzbekistan"),
        ("Turkmenistan", "Uzbekistan"),
        ("Kyrgyzstan", "Uzbekistan"),
        ("Afghanistan", "Uzbekistan"),
        ("Tajikistan", "Uzbekistan"),
        ("Pakistan", "Tajikistan"),
        ("China", "Tajikistan"),
        ("Kyrgyzstan", "Tajikistan"),
        ("Afghanistan", "Tajikistan"),
        ("China", "Kyrgyzstan"),
        ("Pakistan", "Turkmenistan"),
        ("Afghanistan", "Turkmenistan"),
        ("Iran", "Turkmenistan"),
        ("Armenia", "Georgia"),
        ("Armenia", "Turkey"),
        ("Armenia", "Azerbaijan"),
        ("Armenia", "Iran"),
        ("China", "Japan"),
        ("Bangladesh", "China"),
        ("China", "Laos"),
        ("China", "Taiwan"),
        ("China", "North Korea"),
        ("Bhutan", "China"),
        ("China", "Nepal"),
        ("China", "Philippines"),
        ("China", "South Korea"),
        ("China", "India"),
        ("China", "Mongolia"),
        ("China", "Myanmar"),
        ("China", "Pakistan"),
        ("China", "Vietnam"),
        ("Afghanistan", "China"),
        ("China", "Thailand"),
        ("Azerbaijan", "Georgia"),
        ("Azerbaijan", "Turkey"),
        ("Azerbaijan", "Iran"),
        ("Georgia", "Turkey"),
        ("Afghanistan", "Pakistan"),
        ("Afghanistan", "Iran"),
        ("Afghanistan", "India"),
        ("Iran", "Pakistan"),
        ("Iran", "United Arab Emirates"),
        ("Iran", "Turkey"),
        ("Iran", "Kuwait"),
        ("Iran", "Saudi Arabia"),
        ("Iran", "Iraq"),
        ("Iran", "Qatar"),
        ("Iran", "Oman"),
        ("Indonesia", "Papua New Guinea"),
        ("Indonesia", "Malaysia"),
        ("Brunei", "Indonesia"),
        ("Indonesia", "Timor-Leste"),
        ("Malaysia", "Philippines"),
        ("Brunei", "Malaysia"),
        ("Malaysia", "Thailand"),
        ("Argentina", "Falkland Is."),
        ("Argentina", "Paraguay"),
        ("Argentina", "Uruguay"),
        ("Chad", "Nigeria"),
        ("Benin", "Nigeria"),
        ("Niger", "Nigeria"),
        ("Central African Rep.", "Nigeria"),
        ("Cameroon", "Nigeria"),
        ("Cameroon", "Gabon"),
        ("Cameroon", "Niger"),
        ("Cameroon", "Chad"),
        ("Cameroon", "Eq. Guinea"),
        ("Cameroon", "Central African Rep."),
        ("Cameroon", "Congo"),
        ("Central African Rep.", "Sudan"),
        ("Central African Rep.", "Chad"),
        ("Central African Rep.", "S. Sudan"),
        ("Central African Rep.", "Congo"),
        ("Congo", "Gabon"),
        ("Congo", "Eq. Guinea"),
        ("Eq. Guinea", "Gabon"),
        ("S. Sudan", "Sudan"),
        ("Ethiopia", "S. Sudan"),
        ("Djibouti", "Somalia"),
        ("Somalia", "Somaliland"),
        ("Ethiopia", "Somalia"),
        ("Djibouti", "Ethiopia"),
        ("Ethiopia", "Yemen"),
        ("Ethiopia", "Somaliland"),
        ("Eritrea", "Ethiopia"),
        ("Ethiopia", "Sudan"),
        ("Djibouti", "Yemen"),
        ("Djibouti", "Somaliland"),
        ("Djibouti", "Eritrea"),
        ("Eritrea", "Sudan"),
        ("Chad", "Sudan"),
        ("Libya", "Sudan"),
        ("Saudi Arabia", "Sudan"),
        ("Egypt", "Sudan"),
        ("Chad", "Niger"),
        ("Chad", "Libya"),
        ("Eritrea", "Yemen"),
        ("Eritrea", "Saudi Arabia"),
        ("Saudi Arabia", "Yemen"),
        ("Oman", "Saudi Arabia"),
        ("Palestine", "Saudi Arabia"),
        ("Saudi Arabia", "United Arab Emirates"),
        ("Jordan", "Saudi Arabia"),
        ("Kuwait", "Saudi Arabia"),
        ("Iraq", "Saudi Arabia"),
        ("Qatar", "Saudi Arabia"),
        ("Egypt", "Saudi Arabia"),
        ("Israel", "Saudi Arabia"),
        ("Egypt", "Palestine"),
        ("Egypt", "Jordan"),
        ("Egypt", "Libya"),
        ("Egypt", "Israel"),
        ("Libya", "Niger"),
        ("Libya", "Tunisia"),
        ("Benin", "Niger"),
        ("Burkina Faso", "Niger"),
        ("Finland", "Norway"),
        ("Norway", "Sweden"),
        ("Estonia", "Norway"),
        ("Japan", "North Korea"),
        ("North Korea", "South Korea"),
        ("Estonia", "Sweden"),
        ("Lithuania", "Sweden"),
        ("Denmark", "Sweden"),
        ("Finland", "Sweden"),
        ("Belarus", "Sweden"),
        ("Latvia", "Sweden"),
        ("Belarus", "Ukraine"),
        ("Belarus", "Lithuania"),
        ("Belarus", "Poland"),
        ("Belarus", "Latvia"),
        ("Slovakia", "Ukraine"),
        ("Romania", "Ukraine"),
        ("Poland", "Ukraine"),
        ("Serbia", "Ukraine"),
        ("Hungary", "Ukraine"),
        ("Moldova", "Ukraine"),
        ("Austria", "Poland"),
        ("Germany", "Poland"),
        ("Lithuania", "Poland"),
        ("Poland", "Slovakia"),
        ("Czechia", "Poland"),
        ("Austria", "Germany"),
        ("Austria", "Slovenia"),
        ("Austria", "Slovakia"),
        ("Austria", "Croatia"),
        ("Austria", "Switzerland"),
        ("Austria", "Czechia"),
        ("Austria", "Italy"),
        ("Austria", "Hungary"),
        ("Hungary", "Slovenia"),
        ("Hungary", "Slovakia"),
        ("Hungary", "Romania"),
        ("Croatia", "Hungary"),
        ("Czechia", "Hungary"),
        ("Hungary", "Italy"),
        ("Hungary", "Serbia"),
        ("Moldova", "Romania"),
        ("Romania", "Slovakia"),
        ("Romania", "Serbia"),
        ("Bulgaria", "Romania"),
        ("Latvia", "Lithuania"),
        ("Estonia", "Latvia"),
        ("Germany", "Luxembourg"),
        ("Denmark", "Germany"),
        ("Belgium", "Germany"),
        ("Germany", "Netherlands"),
        ("Czechia", "Germany"),
        ("Germany", "Switzerland"),
        ("Bulgaria", "Greece"),
        ("Bulgaria", "North Macedonia"),
        ("Bulgaria", "Turkey"),
        ("Bulgaria", "Serbia"),
        ("Albania", "Greece"),
        ("Greece", "North Macedonia"),
        ("Greece", "Turkey"),
        ("Iraq", "Turkey"),
        ("Syria", "Turkey"),
        ("Albania", "North Macedonia"),
        ("Albania", "Kosovo"),
        ("Albania", "Bosnia and Herz."),
        ("Albania", "Croatia"),
        ("Albania", "Montenegro"),
        ("Albania", "Serbia"),
        ("Bosnia and Herz.", "Croatia"),
        ("Croatia", "Slovenia"),
        ("Croatia", "Italy"),
        ("Croatia", "Montenegro"),
        ("Croatia", "Serbia"),
        ("Italy", "Switzerland"),
        ("Belgium", "Luxembourg"),
        ("Belgium", "Netherlands"),
        ("Portugal", "Spain"),
        ("Ireland", "United Kingdom"),
        ("Bosnia and Herz.", "Italy"),
        ("Italy", "Slovenia"),
        ("Italy", "Tunisia"),
        ("Italy", "Montenegro"),
        ("Czechia", "Slovakia"),
        ("Japan", "South Korea"),
        ("Bosnia and Herz.", "Montenegro"),
        ("Bosnia and Herz.", "Serbia"),
        ("Kosovo", "North Macedonia"),
        ("North Macedonia", "Serbia"),
        ("Kosovo", "Serbia"),
        ("Montenegro", "Serbia"),
        ("Kosovo", "Montenegro"),
        ("South Africa", "eSwatini"),
        ("Lesotho", "South Africa"),
        ("Honduras", "Nicaragua"),
        ("Costa Rica", "Nicaragua"),
        ("Belize", "Honduras"),
        ("Guatemala", "Honduras"),
        ("El Salvador", "Honduras"),
        ("Belize", "Guatemala"),
        ("El Salvador", "Guatemala"),
        ("Colombia", "Ecuador"),
        ("Colombia", "Panama"),
        ("Colombia", "Venezuela"),
        ("Trinidad and Tobago", "Venezuela"),
        ("Guyana", "Venezuela"),
        ("Guyana", "Suriname"),
        ("Costa Rica", "Panama"),
        ("Guinea-Bissau", "Senegal"),
        ("Guinea", "Senegal"),
        ("Gambia", "Senegal"),
        ("Benin", "Ghana"),
        ("Benin", "Burkina Faso"),
        ("Benin", "Togo"),
        ("Ghana", "Togo"),
        ("Burkina Faso", "Togo"),
        ("Burkina Faso", "Ghana"),
        ("Côte d'Ivoire", "Ghana"),
        ("Côte d'Ivoire", "Liberia"),
        ("Burkina Faso", "Côte d'Ivoire"),
        ("Côte d'Ivoire", "Guinea"),
        ("Guinea", "Liberia"),
        ("Guinea", "Guinea-Bissau"),
        ("Guinea", "Sierra Leone"),
        ("Liberia", "Sierra Leone"),
        ("Israel", "Palestine"),
        ("Israel", "Jordan"),
        ("Israel", "Syria"),
        ("Israel", "Lebanon"),
        ("Jordan", "Lebanon"),
        ("Lebanon", "Syria"),
        ("Jordan", "Palestine"),
        ("Iraq", "Jordan"),
        ("Jordan", "Syria"),
        ("Iraq", "Syria"),
        ("Iraq", "Kuwait"),
        ("Qatar", "United Arab Emirates"),
        ("Oman", "United Arab Emirates"),
        ("Oman", "Yemen"),
        ("Cambodia", "Vietnam"),
        ("Cambodia", "Laos"),
        ("Cambodia", "Thailand"),
        ("Laos", "Thailand"),
        ("India", "Thailand"),
        ("Thailand", "Vietnam"),
        ("Myanmar", "Thailand"),
        ("Laos", "Vietnam"),
        ("Laos", "Myanmar"),
        ("India", "Myanmar"),
        ("Bangladesh", "Myanmar"),
        ("India", "Pakistan"),
        ("India", "Nepal"),
        ("Bhutan", "India"),
        ("India", "Sri Lanka"),
        ("Bangladesh", "India"),
        ("Bangladesh", "Nepal"),
        ("Cyprus", "N. Cyprus"),
    ]
}

/// Build a map from nation name to list of neighboring nations
pub fn build_nation_adjacency_map() -> HashMap<String, Vec<String>> {
    let borders = get_nation_borders();
    let mut map: HashMap<String, Vec<String>> = HashMap::new();
    
    for (country_a, country_b) in borders {
        map.entry(country_a.to_string())
            .or_insert_with(Vec::new)
            .push(country_b.to_string());
        
        map.entry(country_b.to_string())
            .or_insert_with(Vec::new)
            .push(country_a.to_string());
    }
    
    map
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_border_count() {
        let borders = get_nation_borders();
        assert!(!borders.is_empty(), "Should have border data");
    }

    #[test]
    fn test_adjacency_map() {
        let map = build_nation_adjacency_map();
        assert!(!map.is_empty(), "Adjacency map should not be empty");
        
        // Test that borders are bidirectional
        for (country, neighbors) in &map {
            for neighbor in neighbors {
                let neighbor_list = map.get(neighbor).unwrap();
                assert!(
                    neighbor_list.contains(country),
                    "Border {} <-> {} should be bidirectional",
                    country,
                    neighbor
                );
            }
        }
    }
}
